[build]
builder = "dockerfile" 
dockerfilePath = "Dockerfile.client"
buildArgs = ["REACT_APP_API_URL", "REACT_APP_SOCKET_URL"]

[deploy]
numReplicas = 1
sleepApplication = false
healthcheckPath = "/"
healthcheckTimeout = 100

[build.watchPaths]
include = ["client/**", "Dockerfile.client", "nginx.conf"]
ignore = ["backend/**", "eventserver/**"]