[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.eventserver"

[deploy]
numReplicas = 1
sleepApplication = false  
healthcheckPath = "/health"
healthcheckTimeout = 100

[build.watchPaths]
include = ["eventserver/**", "Dockerfile.eventserver"]
ignore = ["client/**", "backend/**"]